package ge.tbc.testautomation.tbcbankapp.performance.utils;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;

/**
 * Launches k6 as a subprocess for a given script resource on the classpath.
 *
 * Why the temp-copy step:
 *   k6 requires a real filesystem path — it cannot run a script from a jar:// URL.
 *   We extract the .js to a temp directory alongside a copy of performance_feeder.csv,
 *   because k6 resolves open('performance_feeder.csv') relative to the directory
 *   the script lives in.
 *
 * k6 must be installed globally and available on PATH.
 * CI note: install k6 on your runner before the Maven test step.
 *   GitHub Actions → uses: grafana/setup-k6-action@v1
 *   GitLab CI      → before_script: apt-get install -y k6
 */
public class K6Runner {

    public record K6Result(int exitCode, boolean thresholdsPassed) {}

    /**
     * Resolves a k6 script from the classpath, extracts it to a temp directory
     * alongside the feeder CSV, then runs k6 against it.
     *
     * @param classpathResource e.g. "performance/smoke_test.js"
     * @param feederCsvPath     absolute path to performance_feeder.csv (generated by PerformanceBase)
     * @return K6Result with exit code and whether all thresholds passed
     */
    public static K6Result run(String classpathResource, Path feederCsvPath) throws Exception {
        Path tempDir = extractScriptToTemp(classpathResource, feederCsvPath);
        Path scriptFile = tempDir.resolve(Path.of(classpathResource).getFileName());

        return executeK6(scriptFile, tempDir);
    }

    // -------------------------------------------------------------------------
    // Extract .js from classpath + copy CSV into the same temp directory
    // -------------------------------------------------------------------------

    private static Path extractScriptToTemp(String classpathResource, Path feederCsvPath)
            throws IOException {

        URL resourceUrl = K6Runner.class.getClassLoader().getResource(classpathResource);
        if (resourceUrl == null) {
            throw new IllegalArgumentException(
                    "Classpath resource not found: " + classpathResource +
                            "\nEnsure the file exists under src/main/resources/" + classpathResource
            );
        }

        // Temp directory scoped to this k6 run; cleaned up on JVM exit
        Path tempDir = Files.createTempDirectory("k6-run-");
        tempDir.toFile().deleteOnExit();

        // Copy the .js script into temp dir
        String scriptFileName = Path.of(classpathResource).getFileName().toString();
        Path tempScript = tempDir.resolve(scriptFileName);
        try (InputStream in = resourceUrl.openStream()) {
            Files.copy(in, tempScript, StandardCopyOption.REPLACE_EXISTING);
        }

        // Copy the feeder CSV alongside the script so k6's open('performance_feeder.csv') resolves
        Path tempCsv = tempDir.resolve("performance_feeder.csv");
        Files.copy(feederCsvPath, tempCsv, StandardCopyOption.REPLACE_EXISTING);

        System.out.println("[K6Runner] Script extracted to: " + tempScript);
        System.out.println("[K6Runner] Feeder CSV copied to: " + tempCsv);

        return tempDir;
    }

    // -------------------------------------------------------------------------
    // Subprocess execution
    // -------------------------------------------------------------------------

    private static K6Result executeK6(Path scriptFile, Path workingDir) throws Exception {
        ProcessBuilder pb = new ProcessBuilder(
                "k6", "run", scriptFile.toAbsolutePath().toString()
        );
        pb.directory(workingDir.toFile());
        pb.redirectErrorStream(true); // merge stderr into stdout for unified CI log

        System.out.println("[K6Runner] Starting: k6 run " + scriptFile.getFileName());
        System.out.println("[K6Runner] " + "=".repeat(60));

        Process process = pb.start();

        try (BufferedReader reader = new BufferedReader(
                new InputStreamReader(process.getInputStream()))) {
            String line;
            while ((line = reader.readLine()) != null) {
                System.out.println(line);
            }
        }

        int exitCode = process.waitFor();

        System.out.println("[K6Runner] " + "=".repeat(60));
        System.out.println("[K6Runner] Finished with exit code: " + exitCode);

        // k6 exits 0 when all thresholds pass, non-zero when any breach
        return new K6Result(exitCode, exitCode == 0);
    }
}