// Loads and parses performance_feeder.csv into a k6 SharedArray.
// The CSV is generated by CsvFeederWriter.java and sits alongside
// the script in the temp directory at runtime.
//
// Import with: import { testData } from './utils/feederLoader.js';

import { SharedArray } from 'k6/data';

export const testData = new SharedArray('locations', function () {
    return open('../performance_feeder.csv')
        .split('\n')
        .slice(1)                           // skip header row
        .map(line => line.trim())
        .filter(line => line.length > 0)    // drop empty trailing lines
        .map(line => {
            const [id, regionName, type] = line.split(',');
            return {
                regionName: regionName.replace(/"/g, '').trim(),  // strip CSV quotes around Georgian chars
                type: type.trim(),
            };
        });
});

/** Returns a random record from the shared array. */
export function randomRecord() {
    return testData[Math.floor(Math.random() * testData.length)];
}